---
# tasks file for sap-preconfigure: configuration

# Linux-UUID-solutions
- debug:
    msg: "SAP note 1391070: Configure uuidd"

- import_tasks: ../RedHat/generic/assert-uuidd.yml
  when: sap_preconfigure_config_all|d(true) or sap_preconfigure_1391070|d(false)

...
