---
# tasks file for sap-preconfigure configuration

- name: list of required SAP Notes
  debug:
    var: __sap_preconfigure_assert_sapnotes | difference([''])

- name: Gather service facts
  service_facts:

- name: include configuration actions for required sapnotes
  include_tasks: "sapnote/assert-{{ item }}.yml"
  with_items: "{{ __sap_preconfigure_assert_sapnotes | difference(['']) }}"
#- include: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/recommendations.yml' }}"

...
