---
# tasks file for sap-preconfigure-assert

- name: Print deprecation notice
  pause:
    prompt: |
      ""
      "*** NOTE: This role is deprecated. ***"
      ""
      "Role sap_general_preconfigure, when run in assert mode, provides all the features of this role, and more."
      "You can find the role in repository https://www.github.com/sap-linuxlab/community.sap_install ."
      ""
      "Press RETURN to continue anyway, or <ctrl>c, a, to abort:"

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::sap-preconfigure-assert'
    - 'role::sap-preconfigure-assert:install'
    - 'role::sap-preconfigure-assert:config'

- name: Get list of installed packages
  package_facts:
    manager: auto

- import_tasks: installation.yml
  tags:
    - 'role::sap-preconfigure-assert'
    - 'role::sap-preconfigure-assert:install'

- import_tasks: configuration.yml
  tags:
    - 'role::sap-preconfigure-assert'
    - 'role::sap-preconfigure-assert:config'

...
