---
# tasks file for sap-preconfigure-assert

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::sap-preconfigure-assert'
    - 'role::sap-preconfigure-assert:install'
    - 'role::sap-preconfigure-assert:config'

- import_tasks: installation.yml
  tags:
    - 'role::sap-preconfigure-assert'
    - 'role::sap-preconfigure-assert:install'

- import_tasks: configuration.yml
  tags:
    - 'role::sap-preconfigure-assert'
    - 'role::sap-preconfigure-assert:config'

...
