---
# tasks file for sap-preconfigure: configuration

# 03-configure-hostname.yml
- debug:
    msg: "SAP note 2772999 Step 3: Configure Hostname"

- import_tasks: ../../RedHat/generic/assert-hostname.yml
- import_tasks: ../../RedHat/generic/assert-etc-hosts.yml
- import_tasks: ../../RedHat/generic/assert-dns-name-resolution.yml

...
