---
# tasks file for sap-preconfigure: configuration

# 07-configure-tmpfs.yml
- debug:
      msg: "SAP note 2772999 Step 7: Configure tmpfs; memtotal_mb = {{ ansible_memtotal_mb }}; swaptotal_mb = {{ ansible_swaptotal_mb }}; sap_preconfigure_assert_size_of_tmpfs_gb = {{ sap_preconfigure_assert_size_of_tmpfs_gb }}"

- name: Check the size of tmpfs
  command: awk '/\/dev\/shm/&&/tmpfs/&&/{{ sap_preconfigure_assert_size_of_tmpfs_gb }}G/{gsub ("defaults,size=", "", $4); print $4}' /etc/fstab
  register: awk_tmpfs_size_result
  ignore_errors: yes
  changed_when: no

- name: Assert that the size of tmpfs is large enough as per /etc/fstab
  assert:
    that:
      - "'{{ sap_preconfigure_assert_size_of_tmpfs_gb }}G' in awk_tmpfs_size_result.stdout"
    fail_msg: "FAIL: The size of tmpfs in /etc/fstab is '{{ awk_tmpfs_size_result.stdout }}' but the expected size is '{{ sap_preconfigure_assert_size_of_tmpfs_gb }}G!"
    success_msg: "PASS: The size of tmpfs in /etc/fstab is '{{ awk_tmpfs_size_result.stdout }}'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Check if /dev/shm is available and has the expected size
  shell: df -kh /dev/shm | awk '/\/dev\/shm/&&/tmpfs/&&/{{ sap_preconfigure_assert_size_of_tmpfs_gb }}G/{print $2}'
  register: df_result
  ignore_errors: yes
  changed_when: no

- name: Assert that the current size of tmpfs is large enough as per df output
  assert:
    that:
      - "df_result.stdout == '{{ sap_preconfigure_assert_size_of_tmpfs_gb }}G'"
    fail_msg: "FAIL: The current size of tmpfs is '{{ df_result.stdout }}' but the expected size is '{{ sap_preconfigure_assert_size_of_tmpfs_gb }}G!"
    success_msg: "PASS: The current size of tmpfs is '{{ df_result.stdout }}'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

...
