---
# tasks file for sap-preconfigure: configuration

# 09-configure-process-resource-limits.yml
- debug:
    msg: "SAP note 2772999 Step 9: Configure Process Resource Limits"

- name: Check if the hard limit of nofile for group sapsys is 65536
  command: awk '/sapsys/&&/nofile/&&/hard/{print $NF}' /etc/security/limits.d/99-sap.conf
  register: awk_nofile_hard_result
  changed_when: no
  ignore_errors: yes

- name: Assert that the hard limit of nofile for group sapsys is 65536
  assert:
    that:
      - awk_nofile_hard_result.stdout == '65536'
    fail_msg: "FAIL: The hard limit of nofile for group sapsys in /etc/security/limits.d/99-sap.conf is '{{ awk_nofile_hard_result.stdout }}' but the expected value is 2147483647 !"
    success_msg: "PASS: The hard limit of nofile for group sapsys in /etc/security/limits.d/99-sap.conf is '{{ awk_nofile_hard_result.stdout }}'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Check if the soft limit of nofile for group sapsys is 65536
  command: awk '/sapsys/&&/nofile/&&/soft/{print $NF}' /etc/security/limits.d/99-sap.conf
  register: awk_nofile_soft_result
  changed_when: no
  ignore_errors: yes

- name: Assert that the soft limit of nofile for group sapsys is 65536
  assert:
    that:
      - awk_nofile_soft_result.stdout == '65536'
    fail_msg: "FAIL: The soft limit of nofile for group sapsys in /etc/security/limits.d/99-sap.conf is '{{ awk_nofile_soft_result.stdout }}' but the expected value is 2147483647 !"
    success_msg: "PASS: The soft limit of nofile for group sapsys in /etc/security/limits.d/99-sap.conf is '{{ awk_nofile_soft_result.stdout }}'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- debug:
    msg: "WARN: Check of the hard and soft limit of nofile for the database group not implemented. Please check manually!"

...
