---
# tasks file for sap-preconfigure: configuration

# 09-configure-process-resource-limits.yml
- debug:
    msg: "SAP note 2772999 Step 9: Configure Process Resource Limits"

- name: Check if the hard limit of nofile is 65536 for group sapsys
  command: awk '/sapsys/&&/nofile/&&/hard/{print $NF}' /etc/security/limits.d/99-sap.conf
  register: awk_nofile_hard_result
  changed_when: no

- name: Assert that the hard limit of nofile is 65536 for group sapsys
  assert:
    that:
      - awk_nofile_hard_result.stdout == '65536'
    fail_msg: "FAIL: The hard limit of nofile for sapsys in /etc/security/limits.d/99-sap.conf is '{{ awk_nofile_hard_result.stdout }}' but the expected value is 2147483647 !"
    success_msg: "PASS: The hard limit of nofile in /etc/security/limits.d/99-sap.conf is '{{ awk_nofile_hard_result.stdout }}'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Check if the soft limit of nofile is 65536 for group sapsys
  command: awk '/sapsys/&&/nofile/&&/soft/{print $NF}' /etc/security/limits.d/99-sap.conf
  register: awk_nofile_soft_result
  changed_when: no

- name: Assert that the soft limit of nofile is 65536 for group sapsys
  assert:
    that:
      - awk_nofile_soft_result.stdout == '65536'
    fail_msg: "FAIL: The soft limit of nofile for sapsys in /etc/security/limits.d/99-sap.conf is '{{ awk_nofile_soft_result.stdout }}' but the expected value is 2147483647 !"
    success_msg: "PASS: The soft limit of nofile in /etc/security/limits.d/99-sap.conf is '{{ awk_nofile_soft_result.stdout }}'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

#- name: Set the hard and soft limit of nofile to 65536 for the database group
#  pam_limits:
#    dest: /etc/security/limits.d/99-sap.conf
#    domain: "{{ sap_preconfigure_assert_db_group_name }} "
#    limit_item: nofile
#    limit_type: "{{ line_item }}"
#    value: "65536"
#  with_items:
#    - hard
#    - soft
#  loop_control:
#    loop_var: line_item
#  when:
#    - sap_preconfigure_assert_db_group_name is defined

...
