---
# tasks file for sap-preconfigure: configuration

# 03-setting-the-hostname.yml
- debug:
    msg: "SAP note 2002167 Step 3: Setting the Hostname"

- import_tasks: ../../RedHat/generic/assert-hostname.yml
- import_tasks: ../../RedHat/generic/assert-etc-hosts.yml
- import_tasks: ../../RedHat/generic/assert-dns-name-resolution.yml

...
