---
# tasks file for sap-preconfigure: configuration

# 04-linux-kernel-parameters.yml
- debug:
    msg: "SAP note 2002167 Step 4: Linux Kernel Parameters"

- name: Get vm.max_map_count from /etc/sysctl.d/sap.conf
  command: awk 'BEGIN{FS="="}/vm.max_map_count/{print $NF}' /etc/sysctl.d/sap.conf
  register: sap_conf_max_map_count_result
  changed_when: no

- name: Assert that vm.max_map_count is set to 2000000 in /etc/sysctl.d/sap.conf
  assert:
    that:
      - sap_conf_max_map_count_result.stdout == '2000000'
    fail_msg: "FAIL: The value of 'vm.max_map_count' in /etc/sysctl.d/sap.conf is {{ sap_conf_max_map_count_result.stdout }} but the expected value is '2000000'!"
    success_msg: "PASS: The value of 'vm.max_map_count' in /etc/sysctl.d/sap.conf is '{{ sap_conf_max_map_count_result.stdout }}'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Get vm.max_map_count value from sysctl
#  shell: sysctl vm.max_map_count | awk 'BEGIN{FS="="}/vm.max_map_count/{gsub (" ", ""); print $NF}'
  shell: sysctl -n vm.max_map_count
  register: sysctl_max_map_count_result
  changed_when: no

- name: Assert that the value of vm.max_map_count as per sysctl output is 2000000
  assert:
    that:
      - sysctl_max_map_count_result.stdout == '2000000'
    fail_msg: "FAIL: The current value of 'vm.max_map_count' as per sysctl is '{{ sysctl_max_map_count_result.stdout }}' but the expected value is '2000000'!"
    success_msg: "PASS: The current value of 'vm.max_map_count' as per sysctl is '{{ sysctl_max_map_count_result.stdout }}'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Get kernel.sem from /etc/sysctl.d/sap.conf
  shell: awk 'BEGIN{FS="="}/kernel.sem/{print $2}' /etc/sysctl.d/sap.conf | awk '{printf ("%s %s %s %s\n", $1, $2, $3, $4)}'
  register: sap_conf_kernel_sem_result
  changed_when: no

- name: Assert that kernel.sem is set to 1250 256000 100 1024 in /etc/sysctl.d/sap.conf
  assert:
    that:
      - sap_conf_kernel_sem_result.stdout == '1250 256000 100 1024'
    fail_msg: "FAIL: The value of 'kernel.sem' in /etc/sysctl.d/sap.conf is {{ sap_conf_kernel_sem_result.stdout }} but the expected value is '1250 256000 100 1024'!"
    success_msg: "PASS: The value of 'kernel.sem' in /etc/sysctl.d/sap.conf is '{{ sap_conf_kernel_sem_result.stdout }}'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Get kernel.sem value from sysctl
#  shell: sysctl kernel.sem | awk 'BEGIN{FS="="}/kernel.sem/{print $2}' | awk '{printf ("%s %s %s %s\n", $1, $2, $3, $4)}'
  shell: sysctl -n kernel.sem | awk '{gsub ("   ", " "); print}'
  register: sap_conf_kernel_sem_result
  changed_when: no

- name: Assert that the value of kernel.sem as per sysctl output is 1250 256000 100 1024
  assert:
    that:
      - sap_conf_kernel_sem_result.stdout == '1250 256000 100 1024'
    fail_msg: "FAIL: The current value of 'kernel.sem' as per sysctl is '{{ sap_conf_kernel_sem_result.stdout }}' but the expected value is '1250 256000 100 1024'!"
    success_msg: "PASS: The current value of 'kernel.sem' as per sysctl is '{{ sap_conf_kernel_sem_result.stdout }}'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

...
