---
# tasks file for sap-preconfigure: configuration

# 04-process-resource-limits.yml
- debug:
    msg: "SAP note 2002167 Step 5: Process Resource Limits"

- name: Get the hard limit of nofile for group sapsys
  command: awk '/sapsys/&&/nofile/&&/hard/{print $NF}' /etc/security/limits.d/99-sap.conf
  register: awk_nofile_hard_result
  changed_when: no

- name: Assert that the hard limit of nofile for group sapsys is 32800 
  assert:
    that:
      - awk_nofile_hard_result.stdout == '32800'
    fail_msg: "FAIL: The hard limit of nofile for group 'sapsys' is not set to '32800' in /etc/security/limits.d/99-sap.conf!"
    success_msg: "PASS: The hard limit of nofile for group 'sapsys' is set to '32800' in /etc/security/limits.d/99-sap.conf."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Get the soft limit of nofile for group sapsys
  command: awk '/sapsys/&&/nofile/&&/soft/{print $NF}' /etc/security/limits.d/99-sap.conf
  register: awk_nofile_soft_result
  changed_when: no

- name: Assert that the soft limit of nofile for group sapsys is 32800
  assert:
    that:
      - awk_nofile_soft_result.stdout == '32800'
    fail_msg: "FAIL: The soft limit of nofile for group sapsys is not set to '32800' in /etc/security/limits.d/99-sap.conf!"
    success_msg: "PASS: The soft limit of nofile for group sapsys is set to '32800' in /etc/security/limits.d/99-sap.conf."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Get the hard limit of nofile for the database group
  command: "awk '/@{{ sap_preconfigure_assert_db_group_name }}/&&/nofile/&&/hard/{print $NF}' /etc/security/limits.d/99-sap.conf"
  register: awk_db_group_nofile_hard_result
  changed_when: no
  when:
    - sap_preconfigure_assert_db_group_name is defined

- name: Assert that the hard limit of nofile for the database group is 32800 
  assert:
    that:
      - awk_db_group_nofile_hard_result.stdout == '32800'
    fail_msg: "FAIL: The hard limit of nofile for group '{{ sap_preconfigure_assert_db_group_name }}' is not set to '32800' in /etc/security/limits.d/99-sap.conf!"
    success_msg: "PASS: The hard limit of nofile for group '{{ sap_preconfigure_assert_db_group_name }}' is set to '32800' in /etc/security/limits.d/99-sap.conf."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"
  when:
    - sap_preconfigure_assert_db_group_name is defined

- name: Get the soft limit of nofile for the database group
  command: "awk '/@{{ sap_preconfigure_assert_db_group_name }}/&&/nofile/&&/soft/{print $NF}' /etc/security/limits.d/99-sap.conf"
  register: awk_db_group_nofile_soft_result
  changed_when: no
  when:
    - sap_preconfigure_assert_db_group_name is defined

- name: Assert that the soft limit of nofile for the database group is 32800 
  assert:
    that:
      - awk_db_group_nofile_soft_result.stdout == '32800'
    fail_msg: "FAIL: The soft limit of nofile for group '{{ sap_preconfigure_assert_db_group_name }}' is not set to '32800' in /etc/security/limits.d/99-sap.conf!"
    success_msg: "PASS: The soft limit of nofile for group '{{ sap_preconfigure_assert_db_group_name }}' is set to '32800' in /etc/security/limits.d/99-sap.conf."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"
  when:
    - sap_preconfigure_assert_db_group_name is defined

- name: Get the soft limit of nproc for group sapsys
  command: awk '/sapsys/&&/nproc/&&/soft/{print $NF}' /etc/security/limits.d/99-sap.conf
  register: awk_nofile_soft_result
  changed_when: no

- name: Assert that the soft limit of nproc is unlimited for group sapsys
  assert:
    that:
      - awk_nofile_soft_result.stdout == 'unlimited'
    fail_msg: "FAIL: The soft limit of nproc for group 'sapsys' is not set to 'unlimited' in /etc/security/limits.d/99-sap.conf!"
    success_msg: "PASS: The soft limit of nproc for group 'sapsys' is set to 'unlimited' in /etc/security/limits.d/99-sap.conf."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Get the soft limit of nproc for the database group
  command: "awk '/@{{ sap_preconfigure_assert_db_group_name }}/&&/nproc/&&/soft/{print $NF}' /etc/security/limits.d/99-sap.conf"
  register: awk_db_group_nproc_soft_result
  changed_when: no
  when:
    - sap_preconfigure_assert_db_group_name is defined

- name: Assert that the soft limit of nproc for the database group is unlimited 
  assert:
    that:
      - awk_db_group_nproc_soft_result.stdout == 'unlimited'
    fail_msg: "FAIL: The soft limit of nproc for group '{{ sap_preconfigure_assert_db_group_name }}' is not set to 'unlimited' in /etc/security/limits.d/99-sap.conf!"
    success_msg: "PASS: The soft limit of nproc for group '{{ sap_preconfigure_assert_db_group_name }}' is set to 'unlimited' in /etc/security/limits.d/99-sap.conf."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"
  when:
    - sap_preconfigure_assert_db_group_name is defined

...
