---

- debug:
    msg: "imported RedHat/generic/assert-dns-name-resolution.yml"

- debug:
    msg:
      - "sap_hostname = {{ sap_hostname }}"
      - "sap_domain = {{ sap_domain }}"
      - "sap_ip = {{ sap_ip }}"

- name: Check if the DNS domain is set
  assert:
    that:
      not( (sap_domain is undefined) or (sap_domain is none) or (sap_domain | trim == '') )
    fail_msg: "You need to define the variable 'sap_domain' in defaults/main.yml."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors is defined and sap_preconfigure_assert_ignore_errors|bool }}"

- name: Check if IP address for sap_hostname.sap_domain is resolved correctly
  shell: dig {{ sap_hostname }}.{{ sap_domain }} +short
  register: dig_short_result
  ignore_errors: yes
  changed_when: no

- assert:
    that:
      - dig_short_result.stdout == '{{ sap_ip }}'
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

### BUG: dig does not use search path in resolv.con on PPCle
- name: Check if IP address for sap_hostname with search path is resolved correctly
  shell: dig {{ sap_hostname }} +search +short
  register: dig_search_short_result
  changed_when: false
  ignore_errors: true

- assert:
    that:
      - dig_search_short_result.stdout == '{{ sap_ip }}'
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(true) }}"

- name: Check if reverse name resolution is correct
  shell: dig -x {{ sap_ip }} +short
  register: dig_reverse_result
  changed_when: false
  ignore_errors: true

- assert:
    that:
      - dig_reverse_result.stdout == '{{ sap_hostname }}.{{ sap_domain }}.'
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(true) }}"

...
