---

- debug:
    msg: "imported RedHat/generic/assert-systemd-tmpfiles.yml"

- name: Check if file /usr/lib/tmpfiles.d/sap.conf or file /etc/tmpfiles.d/sap.conf exists
  shell: test -f /usr/lib/tmpfiles.d/sap.conf -o -f /etc/tmpfiles.d/sap.conf
  register: sap_conf_result
  ignore_errors: yes
  changed_when: no

- name:
  assert:
    that:
      - sap_conf_result.rc == 0
    fail_msg: 'None of /usr/lib/tmpfiles.d/sap.conf or file /etc/tmpfiles.d/sap.conf exists!'
    success_msg: "PASS: /usr/lib/tmpfiles.d/sap.conf or file /etc/tmpfiles.d/sap.conf exists!"
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

...
